### ISSUE TITLE
failing to compile

### ISSUE THREAD

**Issue by Licenser** [freenas/py-libzfs#16]
Bit off a odd system but I'm trying to compile libzfs on a ARM64 (RPI3) and it fails with:

```
cc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -pipe -fno-strict-aliasing -fPIC -I/usr/src/cddl/lib/libumem -I/usr/src/sys/cddl/compat/opensolaris/ -I/usr/src/sys/cddl/compat/opensolaris -I/usr/src/cddl/compat/opensolaris/include -I/usr/src/cddl/compat/opensolaris/lib/libumem -I/usr/src/cddl/contrib/opensolaris/lib/libzpool/common -I/usr/src/sys/cddl/contrib/opensolaris/common/zfs -I/usr/src/sys/cddl/contrib/opensolaris/uts/common/fs/zfs -I/usr/src/sys/cddl/contrib/opensolaris/uts/common/sys -I/usr/src/cddl/contrib/opensolaris/head -I/usr/src/sys/cddl/contrib/opensolaris/uts/common -I/usr/src/cddl/contrib/opensolaris/lib/libnvpair -I/usr/src/cddl/contrib/opensolaris/lib/libuutil/common -I/usr/src/cddl/contrib/opensolaris/lib/libzfs/common -I/usr/src/cddl/contrib/opensolaris/lib/libzfs_core/common -I/usr/local/include/python3.6m -c libzfs.c -o build/temp.freebsd-12.0-CURRENT-arm64-3.6/libzfs.o -DNEED_SOLARIS_BOOLEAN -D_XPG6 -g -O0
libzfs.c:705:42: error: use of undeclared identifier 'ZFS_MAX_DATASET_NAME_LEN'
  __pyx_e_6libzfs_MAX_DATASET_NAME_LEN = ZFS_MAX_DATASET_NAME_LEN
```

**Comment by jceel** [comment]
What is the exact version FreeBSD version you're using? Please paste output of the following commands: `uname -a` and `uname -K`

**Comment by Licenser** [comment]
Hi!

```
root@rpi3:/usr/src # uname -a
FreeBSD rpi3 12.0-CURRENT FreeBSD 12.0-CURRENT #0 r313109M: Thu Feb  2 16:16:39 MST 2017     raspberry@hive.raspbsd.org:/usr/home/brd/rpi3/crochet/work/obj/arm64.aarch64/usr/src/sys/GENERIC  arm64
root@rpi3:/usr/src # uname -K
1200020
```

is the exact one, I tried just adding a (`and False`) to the related IF statement but the 2nd branch doesn't seem to work either.

**Comment by jceel** [comment]
Can you update to the very latest CURRENT tree and see what happens? The error you're getting is due to API incompatibility - for CURRENT builds we support only latest ZFS API/ABI.

**Comment by Licenser** [comment]
As in compiling a new kernel? Honestly no, even fetching the /usr/src takes about 12 hours on that slow bugger I'll rather live with a hand patched version for the time being :)

**Comment by jceel** [comment]
Can't you cross-compile? :) Potentially, if you switch all the `IF (FREEBSD_VERSION ...` statements (there are 3 IIRC) to use the other branch, it should work.

**Comment by jceel** [comment]
Alternatively, you can patch setup.py to set FREEBSD_VERSION to `1003508`

**Comment by Licenser** [comment]
disclaimer: I've no idea what I'm doing ;)

**Comment by jceel** [comment]
OK, so please do `export UNAME_K=1003508` in shell before running setup.py. That should help and let you compile unmodified sources.

**Comment by Licenser** [comment]
oh awesome that does the trick :D I have no idea why but cool! Much appriciated ^.^

**Comment by jceel** [comment]
Cool! When you upgrade your -CURRENT system you will be able to build py-libzfs without that hack.

**Comment by PeterSprague** [comment]
I'm getting the same error building on latest TrueOS on generic amd64 workstation.  Everything has been updated today including sources git pull.

py-libzfs port also fails with same error.

Above "hack" does not work for me.

S uname -a
FreeBSD xxxxxxxxxxx 12.0-CURRENT FreeBSD 12.0-CURRENT #1 96a971c9a(drm-next): Mon Apr 17 18:50:02 UTC 2017     root@devastator:/usr/obj/usr/src/sys/GENERIC  amd64
$ uname -K
1200027

$ bash
$ export UNAME_K=1200027
$ python3.6 setup.py build
running build
running build_py
creating build/lib.freebsd-12.0-CURRENT-amd64-3.6
copying converter.html -> build/lib.freebsd-12.0-CURRENT-amd64-3.6
copying nvpair.html -> build/lib.freebsd-12.0-CURRENT-amd64-3.6
copying libzfs.html -> build/lib.freebsd-12.0-CURRENT-amd64-3.6
copying libzfs.c -> build/lib.freebsd-12.0-CURRENT-amd64-3.6
running build_ext
skipping 'libzfs.c' Cython extension (up-to-date)
building 'libzfs' extension
cc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -pipe -fstack-protector -fno-strict-aliasing -fPIC -I/usr/src/cddl/lib/libumem -I/usr/src/sys/cddl/compat/opensolaris/ -I/usr/src/sys/cddl/compat/opensolaris -I/usr/src/cddl/compat/opensolaris/include -I/usr/src/cddl/compat/opensolaris/lib/libumem -I/usr/src/cddl/contrib/opensolaris/lib/libzpool/common -I/usr/src/sys/cddl/contrib/opensolaris/common/zfs -I/usr/src/sys/cddl/contrib/opensolaris/uts/common/fs/zfs -I/usr/src/sys/cddl/contrib/opensolaris/uts/common/sys -I/usr/src/cddl/contrib/opensolaris/head -I/usr/src/sys/cddl/contrib/opensolaris/uts/common -I/usr/src/cddl/contrib/opensolaris/lib/libnvpair -I/usr/src/cddl/contrib/opensolaris/lib/libuutil/common -I/usr/src/cddl/contrib/opensolaris/lib/libzfs/common -I/usr/src/cddl/contrib/opensolaris/lib/libzfs_core/common -I/usr/local/include/python3.6m -c libzfs.c -o build/temp.freebsd-12.0-CURRENT-amd64-3.6/libzfs.o -DNEED_SOLARIS_BOOLEAN -D_XPG6 -g -O0
libzfs.c:705:42: error: use of undeclared identifier 'ZFS_MAX_DATASET_NAME_LEN'
  __pyx_e_6libzfs_MAX_DATASET_NAME_LEN = ZFS_MAX_DATASET_NAME_LEN
                                         ^
libzfs.c:19646:73: warning: incompatible pointer to integer conversion passing 'PyObject *' (aka 'struct _object *') to parameter of type 'zfs_type_t'
      [-Wint-conversion]
  __pyx_v_handle = zfs_path_to_zhandle(__pyx_v_self->handle, __pyx_t_1, __pyx_t_3);
                                                                        ^~~~~~~~~
/usr/src/cddl/contrib/opensolaris/lib/libzfs/common/libzfs.h:700:79: note: passing argument to parameter here
extern zfs_handle_t *zfs_path_to_zhandle(libzfs_handle_t *, char *, zfs_type_t);
                                                                              ^
libzfs.c:50733:74: warning: passing 'const char *' to parameter of type 'char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        __pyx_v_ret = zfs_destroy_snaps(__pyx_v_self->__pyx_base.handle, __pyx_v_c_name, 1);
                                                                         ^~~~~~~~~~~~~~
/usr/src/cddl/contrib/opensolaris/lib/libzfs/common/libzfs.h:563:52: note: passing argument to parameter here
extern int zfs_destroy_snaps(zfs_handle_t *, char *, boolean_t);
                                                   ^
2 warnings and 1 error generated.
error: command 'cc' failed with exit status 1

Solution?
