### ISSUE TITLE
build breaks on systems without ZPOOL_STATUS_ERRATA, ZPOOL_STATUS_REBUILDING

### ISSUE THREAD

**Issue by jhgit** [freenas/py-libzfs#198]
After the recent cb31b5438fbd9254ddebbeff852b013dbce21a94 commit, which says the change is to "Properly handle ZPOOL_STATUS_INCOMPATIBLE_FEAT" (but does a lot more than that message documents), the build of py-libzfs breaks on systems which don't have ZPOOL_STATUS_ERRATA nor ZPOOL_STATUS_REBUILDING (such as FreeBSD 12).

**Comment by mvanbaak** [comment]
Fails on 13.0 as well.
See log:
[py39-libzfs-1.1.2022071900.log](https://github.com/truenas/py-libzfs/files/9159066/py39-libzfs-1.1.2022071900.log)

**Comment by nathanjrobertson** [comment]
I'm seeing this bug as well on FreeBSD 12.3.
