### ISSUE TITLE
Segmentation fault on using unexisting key

### ISSUE THREAD

**Issue by mexicarne** [freenas/py-libzfs#2]
It's easy to reproduce:

``` python
>>> import nvpair
>>> nvpair.NVList(0).keys()
[]
>>> nvpair.NVList(1).keys()
Segmentation fault (core dumped)
```

I'm using latest port version in FreeBSD (github tag c0100ab)

**Comment by jceel** [comment]
Well, NVList constructor is defined as follows:
```python
def __init__(self, uintptr_t nvlist=0, otherdict=None):
```

so you are trying to access NVList located at 0x1. Segfault is obvious in that case :) What we are going to do is to hide nvpair implementation completely and make libzfs routines accept pure Python dicts. It will be cleaner and make it harded to shoot yourself in the foot.

**Comment by mexicarne** [comment]
Yep, I wasn't sure what I'm trying to accomplish, but since I was able to trigger segfault, I decided to report it for the case.

**Comment by jceel** [comment]
This should be fixed now - NVList is gone! Now all py-libzfs methods accept plain dicts instead :)

**Comment by mexicarne** [comment]
Great, thank you!
