### ISSUE TITLE
Build failure due to zpool_search_import() missing on FreeBSD-current

### ISSUE THREAD

**Issue by netchild** [freenas/py-libzfs#224]
Hi,

the build of py-libzfs fails on FreeBSD-current due to a missing zpool_Search_import(). As such iocage can not be build and the already existing iocage segfaults.

What's the replacement for zpool_search_import()?

Bye,
Alexander.

**Comment by netchild** [comment]
The symbol is available in libzutil, but nowhere an include file in /usr/include which declares this function.

**Comment by ghost** [comment]
It should build using the sources in /usr/src. zpool_search_import() is in libzutil.h in sys/contrib/openzfs/include/.

**Comment by igalic** [comment]
> As such iocage can not be build and the already existing iocage segfaults.

iocage is out of support: https://github.com/iocage/iocage/pull/1292#issuecomment-1368531213

**Comment by netchild** [comment]
> It should build using the sources in /usr/src. zpool_search_import() is in libzutil.h in sys/contrib/openzfs/include/.

The port doesn't compile in poudriere, and it doesn't when I build it by hand via the port (/usr/src contains the full source tree).

**Comment by netchild** [comment]
> iocage is out of support: [iocage/iocage#1292 (comment)](https://github.com/iocage/iocage/pull/1292#issuecomment-1368531213)

Oooh. Tooooo bad! Any recommendations for a similar tool which is still maintained?

**Comment by igalic** [comment]
see https://wiki.freebsd.org/Containers for a fairly complete and up to date list of what's in and what's our, and what's supported and what's fairly dead

**Comment by ghost** [comment]
The port needs to be updated.

**Comment by ghost** [comment]
I've updated the FreeBSD ports for openzfs/openzfs-kmod and py-libzfs.
