### ISSUE TITLE
automatic convertion from unicode to ascii is broken with python2

### ISSUE THREAD

**Issue by bapt** [freenas/py-libzfs#9]
if you try for example to use py-libzfs with python2 and test
libzfs.ZFS().get_snapshot("something").holds

TypeError: Argument 'key' has incorrect type (expected str, got unicode)

If I remove the header from libzfs.pyx then is works again

**Comment by jceel** [comment]
I believe I fixed this in 9e22fa3, can you confirm on your end?

**Comment by bapt** [comment]
Confirm thanks!
